### ISSUE TITLE
URDF description is incorrect

### ISSUE THREAD

**Issue by adam-slucki** [tooploox/car_robot#1]
The current description of the robot isn't realistic. The actual robot has one joint responsible for steering and one actuator responsible for driving all wheels.

In the current URDF description, there are two joints for steering wheels separately and actuators for each wheel have to be accessed directly to drive them.

The structure of the robot described in the URDF should be modified so:
1. It has one joint responsible for steering.
2. It has one joint responsible for driving all 4 wheels.
3. Meshes used for visualization should remain unchanged.

Here is a good example of proper definition for a robot with Ackermann steering: https://github.com/srmainwaring/steer_bot/tree/c86232658df84a8d3518b480a468e8a260754c9c/steer_bot_description/urdf

**Comment by piotr-marcol-tpx** [comment]
merged to master 
commit: dac7f198165cf6424d36aac51f60432bc1c6ca96
