### ISSUE TITLE
Manage dependencies / create virtual environment

### ISSUE THREAD

**Issue by adam-slucki** [tooploox/car_robot#13]
Currently, the dependencies for python are not listed anywhere. External ROS dependencies also don't seem to be managed well. It's worth looking into how to use rosdep, as well as preparation of the environment.

**Comment by NovusEdge** [comment]
I would like to take this issue up if no one's assigned.

**Comment by adam-slucki** [comment]
Sure thing, thank you! Please notice that we don't have licenses specified anywhere yet. We're going to develop this project under MIT license if you care about such things.

**Comment by NovusEdge** [comment]
> Sure thing, thank you! Please notice that we don't have licenses specified anywhere yet. We're going to develop this project under MIT license if you care about such things.

@adam-slucki, In case you want to add the MIT license a quick way, will be: [this](https://choosealicense.com/licenses/mit/)

Please let me know the details of how I should go about working on this issue, i.e. how do you want the virtual environment implemented and/or any additional things that I should know of.

**Comment by adam-slucki** [comment]
Thanks @NovusEdge , I'll add the license to the repo.

I think that the official way of managing all dependencies for ROS, including python modules, is adding them to package.xml files (in <run_depend> tag in the case of python dependencies).
Part of solving the issue could be verification if indeed this is a popular solution, are there better ways, what about specific versions of python modules etc.
If it's the way to go, then such tags should be added to adequate files.
There could be also a simple Makefile with a command for installing dependencies.

At the end of the day, the goal is to make sure that recreating the environment on new machines doesn't require manual steps. For now, let's assume that the ROS is already installed, so this part doesn't have to be automated.

**Comment by adam-slucki** [comment]
A good solution seems to be creating a setup.py in each package, here's an example: https://github.com/Kinovarobotics/kinova-ros/blob/master/kinova_demo/setup.py
More info: http://ros.org/doc/api/catkin/html/user_guide/setup_dot_py.html
This will allow for installing arbitrary versions of packages available locally or on pypi.

Once the setup.py is created, the line containing `catkin_python_setup()` in CMakeLists.txt should be uncommented.

The file will be executed on running `catkin_make`. 

Haven't check if it introduces any problems though.

**Comment by adam-slucki** [comment]
All dependencies should be managed as suggested by official resources. Each package should have the dependencies specified in package.xml. 

For external python libraries this method should be used: http://docs.ros.org/en/jade/api/catkin/html/howto/format1/python_module_dependencies.html

For custom python libraries this method should be used: https://docs.ros.org/en/api/catkin/html/user_guide/setup_dot_py.html

Additionally, external repositiores to include in catkin workspace are managed with http://wiki.ros.org/vcstool
